name             'hwdmediashare'
maintainer       'David Pando'
maintainer_email 'marpada@users.noreply.github.com '
license          'All rights reserved'
description      'Installs/Configures a LAMP stack for hwdMediaShare'
long_description 'Installs/Configures a LAMP stack for hwdMediaShare'
version          '0.1.1'

depends 'build-essential'
depends 'git'
depends 'curl'
depends 'apache2'
depends 'database'
depends 'mysql', '~> 6.0.12'
depends 'database', '~> 3.1.0'
depends 'php'
depends 'php-fpm'
